### ISSUE TITLE
Add "burn in" period in sharkfin RPC Market

### ISSUE THREAD

**Issue by mesalas** [sbenthall/SHARKFin#122] opened 2022-07-19 14:02 UTC
In ammps the institutions join the simulation over the first 15 days.
Therefore we should not buy and sell targets as well as updating dividends for the first 15 days.
For the first 15 days,  sharkfin should send: buy_target = 0,  sell_target = 0 and dividend = some_constant. after 15 days the buy and sell targets change and the dividend starts moving according to the dividend process.

I guess we can use the same "padding" procedure we use in Chum?

**Comment by sbenthall** [comment] 2022-07-19 14:07
Is this needed for White Shark?

**Comment by mesalas** [comment] 2022-07-19 16:00
I think so. But we can see what happens if we don’t or give them a shorter ramp up period. It might be fine.

**Comment by sbenthall** [comment] 2022-08-08 16:54
One question here: why does it need a constant dividend in the burn-in period?
What happens if it walks?

The issue is that I think we are implicitly trying to target a price/dividend ratio; I guess that is coming from the AMMPS agents. So would a constant dividend cause those agents to anchor on a starting price after the burn-in? Just wondering about the logic here.

**Comment by sbenthall** [comment] 2022-08-10 17:28
Looking into this -- we are not keeping the dividend fixed in the burn-in period in Chum.
We are letting it walk.

**Closed** 2022-08-15 15:50 UTC
Labels: Simulation
