### ISSUE TITLE
with setup.py develop, cannot load sharkfin module from some directories

### ISSUE THREAD

**Issue by nicksawhney** [sbenthall/SHARKFin#68] opened 2022-03-28 03:00 UTC
when installing with the current setup.py, doing so with pip makes the code `from sharkfin import hark_portfolio_agents` throw a ModuleNotFound error. 

When installing with `python setup.py install`, sharkfin is able to be imported, but none of the submodules are detected. This will be important for breaking up the files into submodules (currently in the `modules` branch, #67)

```
Python 3.9.4 (default, Apr  8 2021, 18:23:39)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sharkfin
>>> sharkfin.hark_portfolio_agents
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sharkfin' has no attribute 'hark_portfolio_agents'
>>> dir(sharkfin)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```

I'm not exactly sure what the issue is here, is `setup.py` in the wrong directory?

**Comment by sbenthall** [comment] 2022-03-31 15:02
One question: Why are you running `python setup.py install` ?

To answer your question ... it looks like either `setup.cfg` is not written properly, or the module directory is not configured properly.

**Comment by sbenthall** [comment] 2022-03-31 15:29
Another possibility is that because `hark_portfolio_agents.py` cannot be successfully executed by the python interpreter because of the failure to import util ( #65 ) , that file is not being successfully installed.

One way to test this would be to break that module into submodules as per #67 and see if any of the submodules (which are not erroring) are available when you use `python setup.py install`

**Comment by nicksawhney** [comment] 2022-03-31 16:11
I'm trying to use setup.py so I can run `pip install -e .` on the sharkfin directory and have an editable local development installation. This is how i've developed local libraries before. Is this incorrect? If so, what should I be doing to do a local editable installation?

**Comment by sbenthall** [comment] 2022-03-31 16:27
1) I would follow the README instructions to the letter. Otherwise we aren't standardizing around an installation procedure.
2) Running `pip install -e .` will wind up running `setup.py develop` -- `-e` means 'editable', which corresponds to running setup.py in 'development mode'.
3) `python setup.py install` will install the library as a dependency, not in development mode. Doing a regular installation before installing in development mode is unnecessary.

I don't know how to address the issues you are raising in this ticket because you seem to be going off the script in the README.
But it looks like the HARK dependencies are not yet refered to properly in `setup.cfg` -- which is an incomplete stub that will need to be fleshed out before we finalize SHARKFin as a public package.

For the development installation -- which is currently broken and which we will need to fix before trying to prepare a public package (which would be installed with `setup,py install`) -- the README instructions say to first install requirements with `pip`.

**Comment by nicksawhney** [comment] 2022-03-31 16:59
Running into a new error:
from within the sharkfin home directory everything works as intended. You can `from sharkfin import broker` or `from sharkfin.markets import ammps` and everything works fine. However, if a script is being run from outside that directory, for example in "simulate", the imports fail with `ModuleNotFoundError: No module named 'sharkfin'`. However, from other directories one can do `import population` or `import broker` (without the `sharkfin`) and everything works fine.

 I'm not sure what the issue is here.

**Comment by sbenthall** [comment] 2022-03-31 17:10
You are now reporting on errors that must be happening in a local or forked or branched version of the repository, since the `master` branch does not have the submodule structure from #67 

It would be better if you could either sync up `master` or, if you're working on a larger revision that you would like to change in one piece, make a PR. As is, there's no way to reproduce the ticket and it's technically invalid.

**Comment by nicksawhney** [comment] 2022-03-31 17:13
Reproducing this issue requires navigating to the `modules` branch and running `pip install -e .` as specified in the README

**Comment by nicksawhney** [comment] 2022-03-31 17:16
The same error is thrown on both the master branch and the modules branch if `from sharkfin import hark_portfolio_agents` is called from outside the main `SHARKFin` directory. 
`ImportError: cannot import name 'hark_portfolio_agents' from 'sharkfin' (unknown location)`

**Comment by nicksawhney** [comment] 2022-03-31 17:32
fix has been pushed.

**Comment by sbenthall** [comment] 2022-03-31 17:44
Now I get this.
```
$ python
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sharkfin import hark_portfolio_agents 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sb/projects/ufm/SHARKFin/sharkfin/hark_portfolio_agents.py", line 33, in <module>
    import pnl_utils.py.pnl as pnl
ModuleNotFoundError: No module named 'pnl_utils'
>>> 
```

**Comment by sbenthall** [comment] 2022-03-31 17:44
Same error when I run tests.

**Comment by nicksawhney** [comment] 2022-03-31 17:52
Should be fixed. There are some tests that fail that shouldn't fail in the `modules` directory once the import error is resolved. They all have to do with PNL.

**Comment by sbenthall** [comment] 2022-03-31 17:54
If there is some work-in-progress that you would like to discuss, it would be best to make a PR for it (say, from the branch to master) and have the discussion there.

**Comment by nicksawhney** [comment] 2022-03-31 18:04
well, there's still the import issue present, which is not just a work-in-progress feature as it is present on the master branch as well. If there's any more details about the error or if it's unreproducible I'm happy to provide more details, or should I create a new issue for the ongoing setup/import issues?

**Comment by sbenthall** [comment] 2022-03-31 18:40
I see. I was able to reproduce this issue. I've changed the title of this issue to better reflect the current state of the problem.

**Comment by sbenthall** [comment] 2022-03-31 19:09
See commit [54b98](https://github.com/sbenthall/SHARKFin/commit/54b9890400395a87218daf0eeb5ddc7533d59df9) 

I've corrected the `setup.cfg` so that it is correctly matching the flat package layout (i.e., the `sharkfin` package directory is in the root of the repository).

I believe this corrects the error that you were getting. Can you please try it and close the ticket if resolved?

In the future, we will need to keep `setup.cfg` consistent with our source code.

https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

**Comment by nicksawhney** [comment] 2022-03-31 19:51
This makes importing from the root SHARKFin directory work fine. However, importing from the `simulate` directory or from outside the project, within the same virtual environment, throws a `ModuleNotFoundError: No module named 'sharkfin'`

**Comment by sbenthall** [comment] 2022-03-31 20:32
Ok, I'm not able to replicate that based on your description. I'm in `simulate` and `import sharkfin` works fine.

Can you describe the steps that reproduce the problem for you?

**Comment by nicksawhney** [comment] 2022-03-31 20:37
Create a new virtual environment 
`pip install -r requirements.txt` 
`pip install -e .`
`cd simulate`
`python`

```
Python 3.9.10 (main, Jan 15 2022, 11:48:15)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sharkfin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'sharkfin'
```

**Comment by sbenthall** [comment] 2022-03-31 20:59
Ok. I just tried those steps exactly and was not able to reproduce the error. `import sharkfin` from that directory works for me.

Are you sure you've pulled the commit with the new setup.cfg?

If that's not the issue, then this is a hairy problem indeed. It may have to do with differences in the local environment.
One thing to check is `path.sys`.

This is what I'm getting from the `simulate` directory after a fresh installation to a new virtual env:
```
$ python
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sharkfin
>>> import sys
>>> sys.path
['', '/usr/lib/python39.zip', '/usr/lib/python3.9', '/usr/lib/python3.9/lib-dynload', '/home/sb/projects/ufm/SHARKFin/shve2/lib/python3.9/site-packages', '/home/sb/projects/ufm/SHARKFin']
```

**Comment by sbenthall** [comment] 2022-04-01 19:16
This has been verified as fixed by @nicksawhney with the corrected setup.cfg

**Closed by sbenthall** 2022-04-01 19:16 UTC
